// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI47RPljTzCfQvIizDuhWtzzIBx70Dg_M',
    appId: '1:621750741464:web:51c19fb92abdab0c936aad',
    messagingSenderId: '621750741464',
    projectId: 'team-task-management-app-ab197',
    authDomain: 'team-task-management-app-ab197.firebaseapp.com',
    storageBucket: 'team-task-management-app-ab197.firebasestorage.app',
    measurementId: 'G-9D2ZRV1R5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpi2iNwLPQ8kqOShoJYmfDi9C4AvtCfv8',
    appId: '1:621750741464:android:b8382a91317262ea936aad',
    messagingSenderId: '621750741464',
    projectId: 'team-task-management-app-ab197',
    storageBucket: 'team-task-management-app-ab197.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPCQfQGsVTD7QJnqUTjQqvQMRik07SsQ',
    appId: '1:621750741464:ios:f27a70d07bd6bd80936aad',
    messagingSenderId: '621750741464',
    projectId: 'team-task-management-app-ab197',
    storageBucket: 'team-task-management-app-ab197.firebasestorage.app',
    iosBundleId: 'com.example.teamTaskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPCQfQGsVTD7QJnqUTjQqvQMRik07SsQ',
    appId: '1:621750741464:ios:f27a70d07bd6bd80936aad',
    messagingSenderId: '621750741464',
    projectId: 'team-task-management-app-ab197',
    storageBucket: 'team-task-management-app-ab197.firebasestorage.app',
    iosBundleId: 'com.example.teamTaskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI47RPljTzCfQvIizDuhWtzzIBx70Dg_M',
    appId: '1:621750741464:web:a06ed2435dc292ca936aad',
    messagingSenderId: '621750741464',
    projectId: 'team-task-management-app-ab197',
    authDomain: 'team-task-management-app-ab197.firebaseapp.com',
    storageBucket: 'team-task-management-app-ab197.firebasestorage.app',
    measurementId: 'G-0R37TVEWL6',
  );
}
